name: Node.js Package

on:
  release:
    types: [created]
  push:
    tags:
      - '*'           # Push events to every tag not containing /

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: 16
#      - run: npm ci
#      - run: npm run build
#      - run: npm run test

  publish-gpr:
#    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
      - run: |
          npm ci
          npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
